name: Deploy AI Aggregator to GitHub Pages
# This workflow is specifically for the BaiP-ai/aggregator repository
# It includes multiple safeguards to ensure it only runs on the correct repository:
# 1. Job-level 'if' conditions checking github.repository
# 2. Explicit repository verification step with error handling
on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [ main ]
  # Run daily at midnight UTC to keep data fresh
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only run on the BaiP-ai/aggregator repository
    if: github.repository == 'BaiP-ai/aggregator'
    steps:
      - name: Verify repository
        run: |
          echo "Running on repository: ${{ github.repository }}"
          echo "Expected repository: BaiP-ai/aggregator"
          if [ "${{ github.repository }}" != "BaiP-ai/aggregator" ]; then
            echo "ERROR: This workflow should only run on BaiP-ai/aggregator"
            exit 1
          fi
          
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Set up environment for custom data preparation
      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      # Run the data preparation scripts
      - name: Fetch data
        run: node scripts/fetch-data.js

      - name: Ensure logo fields exist
        run: node scripts/ensure-logo-fields.js

      - name: Process data
        run: node scripts/process-data.js

      - name: Verify logo directory
        run: |
          echo "Checking logo directory contents..."
          if [ -d "public/images/logos" ]; then
            echo "✅ Logo directory exists"
            echo "📁 Logo files found:"
            ls -la public/images/logos/ | head -20
            echo "📊 Total logo files: $(find public/images/logos/ -name '*.png' -o -name '*.svg' -o -name '*.jpg' | wc -l)"
          else
            echo "❌ Logo directory not found!"
            echo "Available directories:"
            find . -name "logos" -type d
          fi

      - name: Validate data
        run: node scripts/validate-data.js

      # Build the site using custom build script that ensures logos are copied
      - name: Build site with logos
        run: npm run build-with-logos
        env:
          # Pass environment variables to the build
          BASE_URL: /aggregator
          SITE: https://www.baip.ai
          DISABLE_API_CALLS: true
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      # Ensure logos are copied to dist directory
      - name: Ensure logos are copied to dist
        run: |
          echo "🔧 Ensuring logos are properly copied to dist..."
          
          # Check if public/images/logos exists and has content
          if [ -d "public/images/logos" ] && [ "$(ls -A public/images/logos)" ]; then
            echo "✅ Source logos found in public/images/logos"
            echo "📊 Source logos: $(find public/images/logos/ -name '*.png' -o -name '*.svg' -o -name '*.jpg' | wc -l)"
            
            # Ensure dist/images/logos directory exists
            mkdir -p dist/images/logos
            
            # Copy all logos from public to dist (in case Astro didn't copy them)
            cp -r public/images/logos/* dist/images/logos/ 2>/dev/null || echo "⚠️  No files to copy or already copied"
            
            echo "✅ Manual copy completed"
            echo "📊 Dist logos after copy: $(find dist/images/logos/ -name '*.png' -o -name '*.svg' -o -name '*.jpg' | wc -l)"
          else
            echo "❌ No source logos found in public/images/logos"
          fi
      
      # Verify dist directory exists
      - name: Verify dist directory
        run: |
          if [ ! -d "dist" ]; then
            echo "::error::dist directory not found!"
            ls -la
            exit 1
          fi
          echo "dist directory found - contents:"
          ls -la dist/

      # Deploy to the BaiP-ai/aggregator repository
      - name: Deploy to GitHub Pages in BaiP-ai/aggregator repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          repository-name: BaiP-ai/aggregator
          branch: gh-pages
          token: ${{ secrets.GH_PAT }}
          clean: true
