name: Deploy AI Aggregator to GitHub Pages
# This workflow is specifically for the BaiP-ai/aggregator repository
# It includes multiple safeguards to ensure it only runs on the correct repository:
# 1. Job-level 'if' conditions checking github.repository
# 2. Explicit repository verification step with error handling
on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [ main ]
  # Run daily at midnight UTC to keep data fresh
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only run on the BaiP-ai/aggregator repository
    if: github.repository == 'BaiP-ai/aggregator'
    steps:
      - name: Verify repository
        run: |
          echo "Running on repository: ${{ github.repository }}"
          echo "Expected repository: BaiP-ai/aggregator"
          if [ "${{ github.repository }}" != "BaiP-ai/aggregator" ]; then
            echo "ERROR: This workflow should only run on BaiP-ai/aggregator"
            exit 1
          fi
          
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Set up environment for custom data preparation
      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      # Cache the logos directory to prevent re-downloading on every deployment
      - name: Cache logos
        uses: actions/cache@v4
        with:
          path: public/images/logos
          key: logos-cache-${{ hashFiles('src/data/tools.js', 'src/data/agents.js') }}
          restore-keys: |
            logos-cache-

      # Cache Astro build artifacts for faster builds
      - name: Cache Astro build
        uses: actions/cache@v4
        with:
          path: |
            cache
            node_modules/.astro
          key: astro-cache-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            astro-cache-${{ hashFiles('package-lock.json') }}-
            astro-cache-

      # Run the data preparation scripts
      - name: Fetch data
        run: node scripts/fetch-data.js

      - name: Ensure logo fields exist
        run: node scripts/ensure-logo-fields.js

      - name: Process data and download logos
        run: node scripts/process-data.js

      - name: Verify logo directory
        run: |
          echo "Checking logo directory contents..."
          if [ -d "public/images/logos" ]; then
            echo "✅ Logo directory exists"
            echo "📁 Logo files found:"
            ls -la public/images/logos/ | head -20
            echo "📊 Total logo files: $(find public/images/logos/ -name '*.png' -o -name '*.svg' -o -name '*.jpg' | wc -l)"
          else
            echo "❌ Logo directory not found!"
            mkdir -p public/images/logos
            echo "Created empty logo directory"
          fi

      - name: Validate data
        run: node scripts/validate-data.js

      # Build the site - Astro will automatically copy public/ to dist/
      - name: Build Astro site
        run: npm run build
        env:
          # Pass environment variables to the build
          BASE_URL: /aggregator
          SITE: https://www.baip.ai
          DISABLE_API_CALLS: true
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      # Verify the build output (Astro should have copied logos automatically)
      - name: Verify deployment structure
        run: |
          echo "🔍 Verifying final deployment structure..."
          
          if [ -d "dist" ]; then
            echo "✅ dist directory exists"
            echo "📊 Total files in dist: $(find dist -type f | wc -l)"
            
            if [ -d "dist/images/logos" ]; then
              echo "✅ Logos directory exists in dist"
              echo "📊 Logo files in dist: $(find dist/images/logos/ -name '*.png' -o -name '*.svg' -o -name '*.jpg' | wc -l)"
            else
              echo "❌ No logos directory in dist - this indicates a build problem"
              echo "Available directories in dist:"
              find dist -type d | head -10
            fi
          else
            echo "❌ dist directory not found!"
            ls -la
            exit 1
          fi

      # Deploy to the BaiP-ai/aggregator repository
      - name: Deploy to GitHub Pages in BaiP-ai/aggregator repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          repository-name: BaiP-ai/aggregator
          branch: gh-pages
          token: ${{ secrets.GH_PAT }}
          clean: true
