name: Push to Public Repository (Staging)

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          
      - name: Set up Git identity
        run: |
          git config --global user.name "zalam003"
          git config --global user.email "zaki.alam@gmail.com"

      - name: Prepare and push to public repository
        run: |
          # Generate timestamp for branch name
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="staging-$TIMESTAMP"
          
          # Create a new timestamped branch from main
          git checkout -b $BRANCH_NAME
          
          # Remove the push-to-public.yml workflow
          rm -f .github/workflows/push-to-public.yml
          
          # Ensure .github/workflows directory exists
          mkdir -p .github/workflows
          
          # Copy deploy.yml to workflows directory
          cp deploy/deploy.yml .github/workflows/deploy.yml
          
          # Add changes to git
          git add -A
          
          # Commit changes
          git commit -m "Prepare for deployment (timestamp: $TIMESTAMP)"
          
          # Push using HTTPS with token
          echo "Pushing to public repository using PAT..."
          if git remote | grep -q public; then
            git remote remove public
          fi
          git remote add public https://x-access-token:${{ secrets.GH_PAT }}@github.com/BaiP-ai/aggregator.git
    
          if git push public $BRANCH_NAME; then
            echo "✅ Successfully pushed to staging branch: $BRANCH_NAME"
          else
            echo "❌ Failed to push to public repository."
            exit 1
          fi
          
          echo "Please review changes and then merge to the main branch"
          echo "Public repository staging branch: https://github.com/BaiP-ai/aggregator/tree/$BRANCH_NAME"
