name: Push to Public Repository (Staging)

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Debug SSH setup
        run: |
          echo "SSH agent is running on PID $SSH_AGENT_PID"
          # Check if any keys are loaded (without revealing the key)
          ssh-add -l || echo "No keys added to SSH agent"
          
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Add GitHub.com to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Prepare and push to public repository
        run: |
          # Generate timestamp for branch name
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="staging-$TIMESTAMP"
          
          # Create a new timestamped branch from main
          git checkout -b $BRANCH_NAME
          
          # Remove the push-to-public.yml workflow
          rm -f .github/workflows/push-to-public.yml
          
          # Ensure .github/workflows directory exists
          mkdir -p .github/workflows
          
          # Copy deploy.yml to workflows directory
          cp deploy/deploy.yml .github/workflows/deploy.yml
          
          # Add changes to git
          git add -A
          
          # Commit changes
          git commit -m "Prepare for deployment (timestamp: $TIMESTAMP)"
          
          # Try SSH first
          echo "Attempting to push with SSH..."
          if git remote | grep -q public; then
            git remote remove public
          fi
          git remote add public git@github.com:BaiP-ai/aggregator.git
          
          if git push public $BRANCH_NAME; then
            echo "✅ Successfully pushed to staging branch using SSH: $BRANCH_NAME"
          else
            echo "SSH push failed, trying with HTTPS and token..."
            # If SSH fails, try with token-based HTTPS
            if [ -n "${{ secrets.GH_PAT }}" ]; then
              if git remote | grep -q public; then
                git remote remove public
              fi
              git remote add public https://${{ secrets.GH_PAT }}@github.com/BaiP-ai/aggregator.git
              git push public $BRANCH_NAME
              echo "✅ Successfully pushed to staging branch using HTTPS: $BRANCH_NAME"
            else
              echo "❌ Failed to push to public repository. GH_PAT secret is not set."
              exit 1
            fi
          fi
          
          echo "Please review changes and then merge to the main branch"
          echo "Public repository staging branch: https://github.com/BaiP-ai/aggregator/tree/$BRANCH_NAME"
